### ISSUE TITLE
建议：Picker 不止可以显示文本

### ISSUE THREAD

**Issue by lingbopro** [apprat/sober#12]
Picker 组件中，无论你在 Picker Item 中放什么，选中时 Picker 上也只会显示这个 Picker Item 中的纯文本内容。

有时，我们希望在 Picker 上显示其它东西，所以可以考虑使 Picker 可以直接显示 Picker Item 的内容，也可以做一个是否启用该选项的属性

不然我就只好回去用 Popup Menu 或者自定义 trigger 了

**Comment by apprat** [comment]
感谢您的建议，但实现起来会很复杂，原因是item的样式对于外部来说是可变的，而对于trigger来说做不到克隆整个元素包括样式来显示。

**Comment by lingbopro** [comment]
那我觉得可以提供一个插槽（仅未指定自定义trigger时可用），用于自定义Picker框上的文本，如果自定义trigger的话实现输入框有点麻烦
