### ISSUE TITLE
建议：Navigation Item 的波纹样式

### ISSUE THREAD

**Issue by lingbopro** [apprat/sober#13]
在 Material 样式中，Navigation 这样的导航栏的子项（Navigation Item）被点击时<sup>（任意位置点击）</sup>，波纹效果似乎是从中间的图标部分（对应 Shadow Root 中的 `div.icon`）触发的，而非整个容器。这也就是说，Ripple 被点击时波纹效果实际上在另一个容器上触发。

这样也许可以使 Navigation Item 和 Ripple 都得到更新？

**Comment by apprat** [comment]
感谢您的建议，会考虑。

**Comment by lingbopro** [comment]
等一下，这个issue关了？
