### ISSUE TITLE
对于 Sober `0.3.0` 的文档问题&小建议

### ISSUE THREAD

**Issue by lingbopro** [apprat/sober#14]
![Sober 0.3.0 更新日志](https://github.com/user-attachments/assets/80806bec-d8e6-4d29-ba93-487a11342554)

这几条，逐条分析：

1. 文档没提
2. 文档中仍称 `fold`，而且我觉得可以提供一个属性，用于控制是否启用自定义折叠值，有时候还是很有用的  
  ![Drawer 的文档开头，仍称 `fold`](https://github.com/user-attachments/assets/e418cd95-79a7-4f62-a18b-aaa07bdd0277)
3. 没啥问题
4. 感觉可以让用户选择方形或圆形
5. 使用 DevTools 分析官网上的例子后发现并没有此修改
  ![DevTools 对 BottomSheet 的分析](https://github.com/user-attachments/assets/783d7d69-9dfe-47b0-8c12-c346002fcc32)
7. 不错，但是还是那句，希望能让用户决定
8. 行
9. 也行

**Comment by apprat** [comment]
感谢指正

**Comment by Minemetero** [comment]
他们家的版本号就没正常过0.3.2到0.3.21
