### ISSUE TITLE
问题：Snackbar静态创建方法不继承Page组件样式

### ISSUE THREAD

**Issue by kdxhub** [apprat/sober#16]
这里有一个简易封装：
```javascript
function msg(Message, ConfirmText) {
  let infoJson={};
  infoJson.text=Message;
  if (ConfirmText==undefined) {infoJson.action="";} else {infoJson.action=ConfirmText;};
  customElements.get('s-snackbar').show(infoJson);
  return infoJson;
};
```

执行后创建一个Snackbar并展示
但是这样创建的Snackbar组件没有继承`s-page`所定义的样式

通过DevTools判断发现原因在于这样创建的Snackbar在Body下面，而不是在`s-page`下面
![静态生成的s-snackbar位置错误](https://github.com/user-attachments/assets/02656196-fbde-4f55-9890-dfd32b6d5c0f)

因此建议增加判断，若存在`s-page`就在该控件下继承
或者强制静态创建的Snackbar使用`s-page`中的样式

**Comment by apprat** [comment]
动态调用 `Snackbar.show` 方法时，它会寻找 <body> 的第一个子元素是否为 `<s-page>`，如果是，它会插入到 `<s-page>` 中，如果不是则插入到 `<body>` 中。所以请确保第一个元素为 `<s-page>`，如果你没办法控制这个行为你依旧可以通过 `Snackbar.show` 传入一个 options.root 来设置插入的根元素。

```js
Snackbar.show({ text: 'hello world', root: document.querySelector('s-page') })
```

**Comment by lingbopro** [comment]
我认为可以先在body的第一个子节点寻找`<s-page>`，找不到再用`document.querySelector`全局寻找

**Comment by kdxhub** [comment]
这个特性竟然完全没有在文档里面提及……（我个人是没找到的）

另外本人发现`{type:"error"}`竟然也是支持处理的
文档也没写

**Comment by lingbopro** [comment]
对，Sober 的文档很不丰富，大多都得看代码，对于用户来说很不友好
