### ISSUE TITLE
静态创建Snackbar没有图标

### ISSUE THREAD

**Issue by kdxhub** [apprat/sober#17]
![IMG_20240928_214113](https://github.com/user-attachments/assets/b04ffe36-8123-4733-a8cd-fa8dab4568be)
![](https://s21.ax1x.com/2024/09/28/pA1usUS.jpg)

如图，按issue#16中的方法创建Snackbar没有图标

即使换用页面内元素也没有用
![](https://s21.ax1x.com/2024/09/28/pA1uy4g.jpg)

**Comment by apprat** [comment]
感谢您的反馈，这个BUG会在下个版本修复。

**Comment by kdxhub** [comment]
![](https://s21.ax1x.com/2024/09/28/pA1uT5F.jpg)
![](https://s21.ax1x.com/2024/09/28/pA1uoUU.jpg)
文档演示也有这个bug

刚刚又进行了一些测试，发现这和浏览器似乎有关系
所以报告一下浏览器版本

设备：Redmi Note 12T Pro / HyperOS 1.0.2 / Android 14
浏览器：
* 图1：Kiwi Browser 124.0.6327.4 （内核Chromium 124）
* 图2：Edge 127.0.2651.111
