### ISSUE TITLE
希望可以获取引用的SoberJS的版本

### ISSUE THREAD

**Issue by kdxhub** [apprat/sober#19]
在写一个基于SoberJS的拓展项目，想要检测引用的SoberJS版本以防止意外发生

目前来看好像只能遍历所有`script`标签再正则依次过滤？

希望增加一个函数可以返回引用的soberjs的版本

**Comment by apprat** [comment]
感谢反馈，但是Sober不会内置版本号等信息，Sober的目标是尽可能的轻量级，增加体积且没有太大意义的信息没有内置的必要性。

**Comment by lingbopro** [comment]
理论上可以根据某个Sober版本的独有特征来辨别？

**Comment by lingbopro** [comment]
不过倒是可以内置一个变量
