### ISSUE TITLE
文本輸入框type為非text樣式問題

### ISSUE THREAD

**Issue by itpleb** [apprat/sober#2]
文本輸入框type=password樣式、樣式會錯誤，要自己加樣式input box mini height=56px才能正常。
挺喜歡當有值時 label縮小顯示在左上角、但是不支持select控件。

**Comment by apprat** [comment]
感谢你的反馈，text-field 下个版本会得到修复，select 也会在下个版本中被添加，不过可能名称不会命名为 `select`，请关注版本号。
