### ISSUE TITLE
一点点关于s-snackbar的建议

### ISSUE THREAD

**Issue by kdxhub** [apprat/sober#22]
~跟snackbar过不去了~

* [ ] 允许用户自定义s-snackbar的弹出方向<br>比如说自定义PC或触屏下弹出方向
  * [ ] 多弄点弹出方向，比如从左到右、从右到左之类
* [ ] 弄个静态的s-snackbar，可以理解为套着s-snackbar外观的容器
* [ ] 添加图标插槽，可以控制是否有图标、图标内容，没有再使用默认图标
* [x] 允许设置超时时间，比如`0`为永不隐藏直到点击按钮
* [ ] 在snackbar下面增加一个可选的倒计时进度条来表明还有多久隐藏
* [x] snackbar可以选择在哪个父控件内弹出而不是一直都在s-page或body下弹出
* [ ] snackbar静态创建时允许使用Html语法
* [ ] **BUG** snackbar在特定文本过长时不会显示右侧确认按钮

**Comment by lingbopro** [comment]
其中有几点我也想到了，我打算整个OR

**Comment by lingbopro** [comment]
> * [ ]  允许设置超时时间，比如`0`为永不隐藏直到点击按钮

这一个其实代码里有，但是文档一直都没更新

https://github.com/apprat/sober/blob/7e8651f86d49851de2ccad3ed27f65e4b0df123c/src/snackbar.ts#L6-L9

**Comment by apprat** [comment]
感谢反馈，是我的疏忽，文档没标注的地方比较多，尤其是方法的参数方面

**Comment by lingbopro** [comment]
![image](https://github.com/user-attachments/assets/0afddfed-c756-4434-b2c3-47500b533672)

这个打包好慢啊，开发体验极其不友好（）

**Comment by apprat** [comment]
> ![image](https://private-user-images.githubusercontent.com/148617407/378141976-0afddfed-c756-4434-b2c3-47500b533672.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzOTI0OTksIm5iZiI6MTcyOTM5MjE5OSwicGF0aCI6Ii8xNDg2MTc0MDcvMzc4MTQxOTc2LTBhZmRkZmVkLWM3NTYtNDQzNC1iMmMzLTQ3NTAwYjUzMzY3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQwMjQzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDEyZDczZTgzNDdjNGNlOTM0ZjZlMjIyNjc5NGRmZjVmYjQwZTcwYmU4NDRkMDk1MzU2M2I0ZmVmN2RjMTE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sRMs3i3pLmnM8M3FPVe0RsVgH5EzC-xu6vVszeJQivk)
> 
> 这个打包好慢啊，开发体验极其不友好（）

只需要运行dev即可

**Comment by lingbopro** [comment]
我试过`dev`，但是打开的是空页面？

另外 `dev` 好像也是用 `tsc` 和 `rollup` 的 `-w` 参数来监听文件（我就是手动用`-w`启动的 `tsc` 和 `rollup`）？

**Comment by lingbopro** [comment]
> * [ ]  添加图标插槽，可以控制是否有图标、图标内容，没有再使用默认图标

这一点我在我的fork里实现了，回头开个PR

**Comment by apprat** [comment]
> 我试过`dev`，但是打开的是空页面？
> 
> 另外 `dev` 好像也是用 `tsc` 和 `rollup` 的 `-w` 参数来监听文件（我就是手动用`-w`启动的 `tsc` 和 `rollup`）？

rollup 打包速度无法作为开发使用，速度太慢，所以用tsc编译，用es module的方式去引入编译后的代码。如果页面是空白页面，可以查看浏览器控制台，也可能是端口被屏蔽，尝试修改端口

**Comment by lingbopro** [comment]
> > 我试过`dev`，但是打开的是空页面？
> > 另外 `dev` 好像也是用 `tsc` 和 `rollup` 的 `-w` 参数来监听文件（我就是手动用`-w`启动的 `tsc` 和 `rollup`）？
> 
> rollup 打包速度无法作为开发使用，速度太慢，所以用tsc编译，用es module的方式去引入编译后的代码。如果页面是空白页面，可以查看浏览器控制台，也可能是端口被屏蔽，尝试修改端口

现在没问题了，浏览器得访问 `http://localhost:1996/test/index.html`，我之前直接访问 `http://localhost:1996/` hhh

**Comment by lingbopro** [comment]
修bug修麻了，改一个bug出来3个新bug...

大概实现了一下功能一，我录个屏发一下

**Comment by lingbopro** [comment]
https://github.com/user-attachments/assets/412d45c5-7e87-4df4-9b78-bfe8d1df9d36

大概就这样，可以看看

PS：中间视频比例变化是用DevTools的设备仿真模拟移动端

**Comment by kdxhub** [comment]
> * [ ]  snackbar静态创建时允许使用Html语法
> * [ ]  **BUG** snackbar在特定文本过长时不会显示右侧确认按钮

好好好又找到两个（）

**Comment by lingbopro** [comment]
> > * [ ]  snackbar静态创建时允许使用Html语法
> > * [ ]  **BUG** snackbar在特定文本过长时不会显示右侧确认按钮
> 
> 好好好又找到两个（）

豪德，立即开干PR（

**Comment by kdxhub** [comment]
建议修改issue完成状态，因为实质上此issue中大部分项目没有在更新日志提及、对应Pull Request也没有完成合并。
可以标记为Won't Fix、help wanted或者Reopen
