### ISSUE TITLE
建议: 下拉选择框组件

### ISSUE THREAD

**Issue by lingbopro** [apprat/sober#3]
非常好的组件库  
但是我在为 [这个repo](https://github.com/Minemetero/Table-Tennis-Counter) 制作功能时发现sober没有下拉选择框组件，或许可以加上  

**附图：**  

我自己用`<s-menu>`和`<s-text-field>`实现的简易下拉框  
![image](https://github.com/apprat/sober/assets/148617407/b99113e1-0a14-431b-8620-2041943b703b)  

[Material.Avalonia](https://github.com/AvaloniaUtils/material.avalonia) 的下拉选择框Demo  
![image](https://github.com/apprat/sober/assets/148617407/dbc25737-597b-4b1a-b61a-13f469c73363)

**Comment by apprat** [comment]
感谢你的反馈，该建议已收到！下一个版本中会得到增加。

**Comment by Minemetero** [comment]
你这命名方式一看就是从我那学的

**Comment by itpleb** [comment]
我是直在里面增加支持select

**Comment by lingbopro** [comment]
> 你这命名方式一看就是从我那学的

em？
