### ISSUE TITLE
请不要移除Sober旧版本资源

### ISSUE THREAD

**Issue by kdxhub** [apprat/sober#31]
**SoberJS在npmjs上的旧版本因未知原因被移除，导致一些依赖旧版本SoberJS却难以升级到新版的项目损坏。**

受影响的版本至少包含从0.2.3到0.2.21，均出现404错误导致项目页面空白。

![Screenshot_2024-12-31-12-14-28-091_com microsoft emmx](https://github.com/user-attachments/assets/e1f956a0-6bd8-489a-9e69-508efe943b2b)

~~另外建议Sober的版本号不要涨得这么快，多个更新可以攒一起发。~~

**Comment by lingbopro** [comment]
see https://github.com/apprat/sober/discussions/18#discussioncomment-11329897

**Comment by kdxhub** [comment]
下载数为0不代表引用数为0，建议还是不要乱删的好……下次做项目把它克隆一份吧，至少是MIT协议随便玩（）

**Comment by lingbopro** [comment]
> 下次做项目把它克隆一份吧，至少是MIT协议随便玩（）

我已经开始整了（）

不过不是fork，是新项目，参考了sober

https://github.com/lingbopro/material-me

（在这说这个是不是不太合适
