### ISSUE TITLE
Nice version......

### ISSUE THREAD

**Issue by Minemetero** [apprat/sober#6]
![image_2024-07-04_121704841](https://github.com/apprat/sober/assets/156386015/a480ab5d-9ecd-44b4-b2bd-659a26d467cc)
2变了13没变
我想说的话和我现在这个issue的编号一样

**Comment by apprat** [comment]
这只是一个巧合，实际上更新了0.2.0版本，0.2.1等，在修复BUG时，最后一位版本号会更新，在破坏性的更新时中间位版本号会更新。

**Comment by Minemetero** [comment]
sober是出什么问题了吗？我基于sober的网页UI炸了

**Comment by Minemetero** [comment]
https://minemetero.github.io/Table-Tennis-Counter/

**Comment by apprat** [comment]
> sober是出什么问题了吗？我基于sober的网页UI炸了

很抱歉，0.1到0.2进行了破坏性的更新，如果你引入的CDN包，建议使用锁定版本号链接。具体方式请参考unpkg

**Comment by Minemetero** [comment]
ha?

**Comment by Minemetero** [comment]
你教我一下HTML的引入方式

**Comment by apprat** [comment]
```html
<script src="https://unpkg.com/sober@0.1.13/dist/sober.min.js"></script>
```

**Comment by Minemetero** [comment]
Thanks
