### ISSUE TITLE
新组件: 下拉浮动对话框

### ISSUE THREAD

**Issue by lingbopro** [apprat/sober#8]
emm，这个组件用语言不好描述名字，大概就是从屏幕下方浮动出来，可以进行一些操作，跟对话框差不多

大概就是这样↓

https://github.com/user-attachments/assets/d74d33d5-e427-42e9-ba2a-80fc228662bd

**Comment by apprat** [comment]
感谢您的反馈，该建议已收到，会优先考虑该组件的开发。
