### ISSUE TITLE
问题：Snackbar 的触发位置

### ISSUE THREAD

**Issue by lingbopro** [apprat/sober#9]
我注意到在当前的 `0.2.19` 版本中，[Snackbar](https://soberjs.com/component/snackbar) 在顶部出现，而不是之前的底部  
但是，[官网的更新日志](https://soberjs.com/introduction/update-log) 中**完全没有提到此更改**，只有 `0.2.0` 的更新日志（而现在版本已经到了 `0.2.19`）  

我认为应该提供一个选项供用户选择是从上方还是下方出现，<s>因为 Material 规范如此 <sup>(好像是吧...)</sup></s>，且有时候下方出现很有用  

<details>
  <summary>附图</summary>
  <img src="https://github.com/user-attachments/assets/e44865e4-b9b0-43f2-bb9f-a6390f406bd7" title="从顶部显示的 Snackbar" />
</details>

------
<sup>顺便问一句，[文档的仓库](https://github.com/apprat/sober-docs) 没了？</sup>

**Comment by apprat** [comment]
很抱歉对你造成困扰，对Snackbar的UI更新是出于很多方面的考虑，在 Google 设计规范中，Snackbar 出现在底部，但是这种设计对于网页在移动端表现很不友好，尤其是在输入错误时的提示，会很容易造成输入法挡住了Snackbar，以及网页空间被输入法压缩时Snackbar出现了中间，权衡利弊之下我们选择调整在顶部出现，在设计规范和用户体验之间，我们更倾向于用户体验而不是完全遵守规范。

对于是否开放选项来设置位置，如果后面赞同的开发者比较多，我们会考虑开放该选项。

**Comment by apprat** [comment]
对于更新日志，目前没有太多精力去编写详细日志，所有精力都放在了新增组件和修复BUG中，后面稳定下来后每次更新会有详细说明

**Comment by lingbopro** [comment]
嗯，改触发位置倒也不难，我回头可以提个PR

**Comment by lingbopro** [comment]
我有个不太靠谱的想法...

把Sober官网开源，这样其他人也可以帮助修改文档和更新日志了（

*(bushi*

**Comment by lingbopro** [comment]
另外Snackbar我觉得可以增加更多位置，比如右上角、左下角什么的
